### PR TITLE
Fix for Sodium 0.6.0-beta.1

### PR DESCRIPTION
**Pull request by LordEnder-Kitty**
The folder structure for sodium was changed to net.caffeinemc from me.jellysquid which caused this mod to break when pressing the button.

### CODE REVIEW

**Comment by theendercore** [comment]
Could this get merged?

**Comment by piemanau** [comment]
I was planning to merge when the release came out, do you think I should merge before then?

**Comment by suerion** [comment]
> I was planning to merge when the release came out, do you think I should merge before then?

i think yes, because it is the most used on 1.21 yet

**Comment by BrailleBennett** [comment]
Does this break compatibility with below 1.6? If so, maybe it's worth waiting, if not, def merge.

**Comment by piemanau** [comment]
It would break the mod however I think a simple if statement would fix it, I will look into it.

**Comment by piemanau** [comment]
Neoforge is a bit broken at the moment but when I get it working I can release it.

**Comment by piemanau** [comment]
NeoForge works in an actual instance however I couldn't get it to open in dev for some reason? If you have an idea as to why that is I would love to hear.

**Pull request merged**
