### PR TITLE
1.18.2

### PR DESCRIPTION
**Pull request by MIOGMIOG**
This adds 1.18.2 support (sodium 0.4.1 support)

### CODE REVIEW

**Comment by MIOGMIOG** [comment]
So far, it's throwing bugs, I'm temporarily closing

**Comment by MIOGMIOG** [comment]
I fixed error

**Comment by MIOGMIOG** [comment]
I fixed error

**Comment by ghost** [comment]
How tf do I download it?

**Comment by piemanau** [comment]
Does this work or do I leave it?

**Comment by MIOGMIOG** [comment]
> Does this work or do I leave it?

Leave it, it still doesn't work even though I've updated the class names.

**Comment by MIOGMIOG** [comment]
I dont know.
obrazek

**Comment by MIOGMIOG** [comment]
I think I found the issue
obrazek

**Comment by MIOGMIOG** [comment]
Do you have discord server?

**Comment by MIOGMIOG** [comment]
It actually works! (But without reeses sodium options) @LimeShulkerBox

**Comment by MIOGMIOG** [comment]
All you have to do is fix the support for the new version of Reeses sodium settings

**Comment by MIOGMIOG** [comment]
**Temporarily incompatible with Reese's sodium options**

**Comment by MIOGMIOG** [comment]
This also fixes [https://github.com/LimeShulkerBox/better-sodium-video-settings/issues/11](https://github.com/LimeShulkerBox/better-sodium-video-settings/issues/11)

**Comment by MIOGMIOG** [comment]
Im looking too [https://github.com/FlashyReese/reeses-sodium-options/compare/mc1.18-1.2.3...mc1.18.2-1.4.2](https://github.com/FlashyReese/reeses-sodium-options/compare/mc1.18-1.2.3...mc1.18.2-1.4.2)

**Comment by MIOGMIOG** [comment]
A lot of things has been changed.

**Comment by piemanau** [comment]
> Do you have discord server?

Yea I do, sorry for some reason I am not getting email notifications. Check the CurseForge page.

If you join the Discord we can talk about it together in there, my personal name and discriminator is: LimeShulkerBox#5322

**Pull request merged**
